@startuml

package from {
    object RawRequest {
        id
        user_id
        hash :string[32]
        raw_data :json
        created_at :dateTime
    }
}

package result {
    object Currency {
        id
        code
    }

    object Account {
        id
        owner_id
        currency_id
        amount
    }

    object Transaction {
        id
        account_id
        created_at :datetime
        amount :numeric
        currency_id
        user_data :text
    }

    object Invoice {
        id
        account_id
        created_at :datetime
        modify_at :datetime
        amount :numeric
        currency_id
        user_data :text
    }

    object ExchangeRate {
        currency_id
        date :date
    }

}

from -right-> result

Account -left-> Currency:c_id
Transaction -down-> Account:a_id
Transaction -down-> Currency:c_id
Invoice -down-> Currency:c_id
Invoice -down-> Account:a_id
ExchangeRate -up-> Currency:c_id
Transaction -left-> Invoice:i_id

@enduml