@startuml

package from {
    object RawRequest {
        id :int:pk
        userId :string
        hash :string(32)
        rawData :json
        createdAt :dateTime
    }
}

package result {
    object Currency {
        id :int:pk
        code :int(3)
        userData :json
    }

    object Account {
        id :int:pk
        ownerId :string
        currencyId :int:fk
        amount
        userData :json
    }

    object Transaction {
        id :int:pk
        accountId :int:fk
        createdAt :dateTime
        amount :numeric
        currencyId :int:fk
        userData :json
    }

    object Invoice {
        id :int:pk
        ownerId :string
        createdAt :dateTime
        modifyAt :dateTime
        amount :numeric
        currencyId :int:fk
        userData :json
    }

    object ExchangeRate {
        fromCurrencyId :int:fk
        toCurrencyId :int:fk
        rate
        date :date
    }

    object ExchangeRateHistory {
        fromCurrency :string(3)
        toCurrency :string(3)
        rate
        date :date
    }

}

from -right-> result

Account -left-> Currency:c_id
Transaction -down-> Account:a_id
Transaction -down-> Currency:c_id
Invoice -down-> Currency:c_id
Invoice -down-> Account:a_id
ExchangeRate -up-> Currency:fc_id
ExchangeRate -up-> Currency:tc_id
Transaction -left-> Invoice:i_id
ExchangeRateHistory -up- ExchangeRate

legend right
  <b>:pk</b> primary key
  <b>:fk</b> foreign key
endlegend

@enduml